CREATE TABLE lyfter_car_rental.automobile(
    id SERIAL PRIMARY KEY,
    brand VARCHAR(20),
    model VARCHAR(20),
    manufacturing_year INTEGER,
    status VARCHAR(20)
);

INSERT INTO lyfter_car_rental.automobile (brand, model, manufacturing_year, status)
VALUES
    ('Subaru', 'Forester', 2005, 'Maintenance'),
    ('Chevrolet', 'Aveo', 2009, 'Available'),
    ('Subaru', 'Legacy', 2007, 'Reserved'),
    ('Toyota', 'Corolla', 2007, 'Rented'),
    ('Chevrolet', 'Tracker', 2024, 'Available'),
    ('Volkswagen', 'Golf', 2022, 'Reserved'),
    ('Chevrolet', 'Onix', 2023, 'Available'),
    ('Renault', 'Logan', 2010, 'Reserved'),
    ('Hyundai', 'Elantra', 2009, 'Rented'),
    ('Renault', 'Duster', 2008, 'Available'),
    ('Kia', 'Rio', 2016, 'Maintenance'),
    ('BMW', 'Serie5', 2006, 'Rented'),
    ('Volkswagen', 'Jetta', 2017, 'Available'),
    ('Volkswagen', 'Tiguan', 2024, 'Maintenance'),
    ('BMW', 'X1', 2007, 'Rented'),
    ('Subaru', 'Outback', 2014, 'Available'),
    ('Fiat', 'Mobi', 2008, 'Reserved'),
    ('Nissan', 'Xtrail', 2016, 'Rented'),
    ('Hyundai', 'Elantra', 2011, 'Maintenance'),
    ('Jeep', 'Renegade', 2024, 'Rented'),
    ('Volkswagen', 'Golf', 2010, 'Reserved'),
    ('Kia', 'Picanto', 2022, 'Rented'),
    ('Subaru', 'Impreza', 2006, 'Rented'),
    ('Fiat', 'Uno', 2015, 'Reserved'),
    ('Nissan', 'Sentra', 2011, 'Maintenance'),
    ('Chevrolet', 'Onix', 2017, 'Reserved'),
    ('Ford', 'Explorer', 2009, 'Rented'),
    ('Jeep', 'Patriot', 2022, 'Maintenance'),
    ('Jeep', 'Patriot', 2018, 'Reserved'),
    ('Hyundai', 'Tucson', 2009, 'Reserved'),
    ('Honda', 'Civic', 2008, 'Rented'),
    ('Subaru', 'Outback', 2018, 'Available'),
    ('Kia', 'Seltos', 2024, 'Reserved'),
    ('Volkswagen', 'Tiguan', 2022, 'Available'),
    ('Subaru', 'Forester', 2022, 'Maintenance'),
    ('Renault', 'Duster', 2008, 'Maintenance'),
    ('Kia', 'Sportage', 2019, 'Available'),
    ('Jeep', 'Wrangler', 2021, 'Rented'),
    ('Volkswagen', 'Jetta', 2014, 'Rented'),
    ('Ford', 'Explorer', 2010, 'Available'),
    ('BMW', 'Serie5', 2020, 'Available'),
    ('Honda', 'CRV', 2014, 'Rented'),
    ('Toyota', 'Camry', 2023, 'Available'),
    ('Honda', 'Fit', 2007, 'Rented'),
    ('Ford', 'Ranger', 2022, 'Rented'),
    ('Nissan', 'March', 2024, 'Reserved'),
    ('Chevrolet', 'Tracker', 2011, 'Maintenance'),
    ('Kia', 'Picanto', 2019, 'Reserved'),
    ('Honda', 'Accord', 2012, 'Available'),
    ('Hyundai', 'Accent', 2023, 'Rented');